--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: myspc
  labels:
    app: spc 
spec:
  minReadySeconds: 5
  replicas: 5
  selector:
    matchLabels:
      app: spc
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: myspc
      labels:
        app: spc
    spec:
      containers:
        - image: akshay0570/ak:latest
          name: myspc-container
          ports:
            - containerPort: 8080
              protocol: TCP
status:
  availableReplicas: 5
  readyReplicas: 5
  replicas: 5
  conditions:
    message: Nothing just learning things
    

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: spc
spec:
  allocateLoadBalancerNodePorts: true
  selector:
    app: spc
  type: LoadBalancer
